intro_fr = """! Cette configuration a été générée automatiquement par alcatel_switch_configurator.py
! Fichier source : {SRC_FILE}
! Veuillez vérifier la configuration avant de l'injecter dans un switch

"""
intro_en = """! This configuration was automatically generated by alcatel_switch_configurator.py
! Source file: {SRC_FILE}
! Please check the configuration before injecting it into a switch

"""

empty_fr = """! AVERTISSEMENT: Cette section est vide ou non-renseignée.
"""

empty_en = """! WARNING: This section is empty or void.
"""

class AlcatelSwLang:
    _l_intro = {"FR" : intro_fr, "EN" : intro_en}
    _l_empty = {"FR" : empty_fr, "EN" : empty_en}
    _l_address = {"FR" : "adresse", "EN" : "address"}
    _l_admin_ip_address = {"FR" : "adresses IP d'administration", "EN" : "administrative IP address"}
    _l_adminpassword =  {"FR" : "mot de passe administrateur", "EN" : "administrator password"}
    _l_allow_write = {"FR" : "droit de modification", "EN" : "allow write"}
    _l_authentication = {"FR" : "authentification", "EN" : "authentication"}
    _l_autorecovery_timer = {"FR" : "minuteur d'auto-recouvrement", "EN" : "autorecovery timer"}
    _l_burst = {"FR" : "burst", "EN" : "burst"}
    _l_by_vlan = {"FR" : "par vlan", "EN" : "by vlan"}
    _l_capacitor_detection_enabled_ports = {"FR" : "ports avec détection de capacité", "EN" : "ports with capacitor detection"}
    _l_cidr = {"FR" : "cidr", "EN" : "cidr"}
    _l_contact =  {"FR" : "contact", "EN" : "contact"}
    _l_default = {"FR" : "par défaut", "EN" : "default"}
    _l_enable = {"FR" : "activé", "EN" : "enable"}
    _l_gateway = {"FR" : "passerelle", "EN" : "gateway"}
    _l_id = {"FR" : "identifiant", "EN" : "identifier"}
    _l_interface_index = {"FR" : "indice de l'interface", "EN" : "interface index"}
    _l_ip = {"FR" : "ip", "EN" : "ip"}
    _l_key = {"FR" : "clé", "EN" : "key"}
    _l_linkagg = {"FR" : "aggrégation de lien", "EN" : "link aggregate"}
    _l_linkagg_vlan_association = {"FR" : "association aggrégat de lien/vlan", "EN" : "link aggregate/vlan association"}
    _l_list = {"FR" : "liste", "EN" : "list"}
    _l_location =  {"FR" : "localisation", "EN" : "location"}
    _l_loop_detection = {"FR" : "détection de boucle", "EN" : "loop detection"}
    _l_mask = {"FR" : "masque", "EN" : "mask"}
    _l_member_ports = {"FR" : "ports membres", "EN" : "member ports"}
    _l_metric = {"FR" : "métrique", "EN" : "metric"}
    _l_minpoll = {"FR" : "minpoll", "EN" : "minpoll"}
    _l_misc = {"FR" : "divers", "EN" : "misc"}
    _l_name =  {"FR" : "nom", "EN" : "name"}
    _l_number_ports = {"FR" : "nombre de ports", "EN" : "number ports"}
    _l_password =  {"FR" : "mot de passe", "EN" : "password"}
    _l_port = {"FR" : "port", "EN" : "port"}
    _l_port_vlan_association = {"FR" : "association port/vlan", "EN" : "port/vlan association"}
    _l_routes = {"FR" : "routes", "EN" : "routes"}
    _l_servers = {"FR" : "serveurs", "EN" : "servers"}
    _l_sysinfo = {"FR" : "informations système", "EN" : "system informations"}
    _l_tagged = {"FR" : "étiqueté", "EN" : "tagged"}
    _l_timezone = {"FR" : "fuseau horaire", "EN" : "time-zone"}
    _l_transmission_timer = {"FR" : "minuteur de transmission", "EN": "transmission timer"}
    _l_users =  {"FR" : "utilisateurs", "EN": "users"}
    _l_vlan = {"FR" : "vlan", "EN" : "vlan"}
    
    def __init__(self, lang):
        self._lang = lang
        for key, value in AlcatelSwLang.__dict__.items():
            if key[0:3] == "_l_":
                setattr(self, key[3:], AlcatelSwLang.__dict__[key][self._lang])